version: '2.1'
services:
  terminalserver:
    build:
      context: .
    image: xrdp
    container_name: uxrdp
    hostname: terminalserver
    restart: always
    shm_size: 1g
    ports:
      - "3390:3389"
      - "2222:22"
    volumes:
      - ./data/ssh/:/etc/ssh/
      - /home/:/home/
